name: Athenz v1.12.x with Jetty 12.x Pull Request

on:
  pull_request:
    branches:
      - master
      - '1.12.x-jetty12'

env:
  GOLANG_VERSION: ^1.22
  NODEJS_VERSION: ^18
  JAVA_VERSION: ^17
  JAVA_DISTRO: temurin
  JAVA_ARCH: x64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          architecture: ${{ env.JAVA_ARCH }}

      - name: Setup ZMS Schema file
        run: cp servers/zms/schema/zms_server.sql servers/zms/src/test/resources/mysql
        
      - name: Build Athenz
        run: mvn -B install